// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenWeatherServicesApp.DBModels;

public partial class Countrieslist
{
    public long CountriesId { get; set; }

    public string CountriesFullName { get; set; }

    public string CountriesSymbol { get; set; }
}