// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenWeatherServicesApp.DBModels;

public partial class Unitsystemsymbol
{
    public long UnitSystemSymbolsId { get; set; }

    public string UnitSystemSymbol1 { get; set; }

    public long UnitSystemId { get; set; }

    public string Description { get; set; }


    public Unitsystem unitsystem { get; set; }
}