// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenWeatherServicesApp.DBModels;

public partial class Unitsystem
{
    public long UnitSystemId { get; set; }

    public string UnitSystemValue { get; set; }

    public ICollection<Unitsystemsymbol> unitsystemsymbols { get; set; }
}