// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OpenWeatherServicesApp.DBModels;

public partial class Weatherpolishdescription
{
    public long WeatherId { get; set; }

    public string EngDesc { get; set; }

    public string PolDesc { get; set; }
}